### PR TITLE
Connected Save Trip button to Saved Trips aside.

### PR DESCRIPTION
**Pull request by kohinrichs**
## Changes
1. Added more steps to the render function in savedTripsList. These steps allow us to match the ids of the objects saved in the savedTrips database to the ids of objects in the other databases so we can access the name properties and print them in the DOM.
2. Some additional CSS to make it look more like our wireframe. (It's not the most responsive. Sorry!)

## Of Note
The notes won't show if you accidentally hit the save button but haven't selected anything from the dropdowns. It saves a new object with "0"s to the database and causes the console to throw errors. This can be fixed by deleting the object in the .json that contains the "0"s/ 

## To Test
1. Serve locally and test that the Saved Trips show when you select options from the dropdowns and save the trip.

### CODE REVIEW

**Comment by BarryShovlin** [comment]
🇹🇭

**Comment by MegSemrad** [comment]
👍

**Comment by imannadeem825** [comment]
💯

**Comment by pazia008** [comment]
👍

**Pull request merged**
